services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    # Command now points to 'main:app' since main.py is in the root of the WORKDIR
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]
    # Mount the local 'app' directory to the container's '/app' directory
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

# NEW SERVICE FOR THE AI AGENT
  agent-worker:
    build:
      context: .
      dockerfile: Dockerfile
    # This command runs our new worker script
    command: ["python", "-m", "agent_worker.worker", "start"]
    volumes:
      - ./app:/app
    env_file:
      - .env
    # This ensures the worker doesn't restart constantly on its own
    restart: on-failure

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    ports:
      - "5432:5432"

volumes:
  postgres_data: