[project]
name = "agconnect"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.116.1",
    "pydantic>=2.11.7",
    "pydantic-ai>=0.4.7",
    "pydantic-settings>=2.10.1",
    "supabase>=2.17.0",
]
